### ISSUE TITLE
Can't make `onServer` calls in event listeners?

### ISSUE THREAD

**Issue by worldsayshi** [agocorona/haste-perch#17]
Use case:

I want to call the server in response to an event:
`addEvent this Change $ \_ -> void $ onServer $ {-... change something ...-}`

But it seems that this is not currently possible with Perch. It seems that PerchM is restricting us to only create event listeners that are in the IO monad. That is:
`addEvent
  :: Event evt =>
     PerchM a1 -> evt -> (EventData evt -> IO ()) -> PerchM a`

But it seems reasonable that we could have something like this:
`addEvent
  :: (Event evt, MonadEvent m) =>
     PerchM a1 -> evt -> (EventData evt -> m ()) -> PerchM a`

... seeing as the wrapped method here, `onEvent`, has the type:
`onEvent
  :: (Event evt, MonadEvent m, IsElem el) =>
     el -> evt -> (EventData evt -> m ()) -> m HandlerInfo`

Am I on the wrong track here? If I get a +1 on the idea that the signature `addEvent
  :: (Event evt, MonadEvent m) => ...` will give me the ability to call onServer in the event listener I'll try to hack on it a bit later. Perhaps there is a simpler solution?

**Comment by agocorona** [comment]
Hi:
unfortunately I dont know the Client monad very well.

I did a version of Perch for the Client monad instead of IO: It is Haste.App. Perch

there, addEvent work in the client monad:

addEvent :: ClientCallback a => Perch -> Event Client a -> a -> Perch

what do you want to do? to trigger something on the server when some event happens?

**Comment by worldsayshi** [comment]
Aha. `Haste.App.Perch`. That is definitely a better solution than the one I started working on. :)
